# Generated by Django 5.2.17 on 2026-09-08 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('tipo', models.CharField(choices=[('cliente', 'Cliente'), ('fornecedor', 'Fornecedor')], default='cliente', max_length=20, verbose_name='tipo')),
                ('documento', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CPF/CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='endereço')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['tipo', 'ativo'], name='cli_tipo_ativo_idx')],
            },
        ),
    ]
