# Generated by Django 5.2.17 on 2026-09-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cliente',
            name='cli_tipo_ativo_idx',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='tipo',
            new_name='papel',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='papel',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('fornecedor', 'Fornecedor')], default='cliente', max_length=20, verbose_name='papel'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_pessoa',
            field=models.CharField(choices=[('pf', 'Pessoa física'), ('pj', 'Pessoa jurídica')], default='pf', max_length=20, verbose_name='tipo de pessoa'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['papel', 'ativo'], name='cli_papel_ativo_idx'),
        ),
    ]