# Generated by Django 5.2.17 on 2026-09-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_backfill_owner_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='notificacoes_ativas',
            field=models.BooleanField(default=True, verbose_name='notificações ativas'),
        ),
    ]
