# Generated by Django 5.2.17 on 2026-09-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='papel',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('fornecedor', 'Fornecedor'), ('ambos', 'Cliente/Fornecedor')], default='cliente', max_length=20, verbose_name='papel'),
        ),
    ]
