# Generated by Django 5.2.17 on 2026-09-11 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CobrancaRecorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='descrição')),
                ('tipo', models.CharField(choices=[('a_receber', 'A receber'), ('a_pagar', 'A pagar')], default='a_receber', max_length=20, verbose_name='tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='valor')),
                ('periodicidade', models.CharField(choices=[('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=20, verbose_name='periodicidade')),
                ('dia_vencimento', models.PositiveSmallIntegerField(default=1, help_text='Dia do mês em que a fatura vence.', verbose_name='dia de vencimento (1 a 31)')),
                ('proxima_cobranca', models.DateField(verbose_name='próxima cobrança')),
                ('ativa', models.BooleanField(default=True, verbose_name='ativa')),
                ('ultima_execucao', models.DateTimeField(blank=True, null=True, verbose_name='última execução')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobrancas_recorrentes', to='clientes.cliente', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'cobrança recorrente',
                'verbose_name_plural': 'cobranças recorrentes',
                'ordering': ['-proxima_cobranca'],
                'constraints': [models.CheckConstraint(condition=models.Q(('dia_vencimento__gte', 1), ('dia_vencimento__lte', 31)), name='cobranca_dia_vencimento_valido', violation_error_message='O dia de vencimento deve estar entre 1 e 31.'), models.CheckConstraint(condition=models.Q(('valor__gte', 0)), name='cobranca_valor_positivo', violation_error_message='O valor da cobrança não pode ser negativo.')],
            },
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='número')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='descrição')),
                ('tipo', models.CharField(choices=[('a_receber', 'A receber'), ('a_pagar', 'A pagar')], default='a_receber', max_length=20, verbose_name='tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='valor')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='status')),
                ('vencimento', models.DateField(verbose_name='vencimento')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='data de pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faturas', to='clientes.cliente', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'fatura',
                'verbose_name_plural': 'faturas',
                'ordering': ['-vencimento'],
                'indexes': [models.Index(fields=['tipo', 'status', 'vencimento'], name='fat_tipo_status_venc'), models.Index(fields=['status', 'vencimento'], name='fat_status_venc_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('valor__gte', 0)), name='fatura_valor_positivo', violation_error_message='O valor da fatura não pode ser negativo.')],
            },
        ),
    ]
