# Generated by Django 5.2.17 on 2026-09-11 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrancarecorrente',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cobrancas_recorrentes', to=settings.AUTH_USER_MODEL, verbose_name='dono'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to=settings.AUTH_USER_MODEL, verbose_name='dono'),
        ),
    ]
