# Generated by Django 5.2.17 on 2026-09-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0003_backfill_owner_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='lembrete_previo_enviado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='lembrete prévio enviado em'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='lembrete_vencimento_enviado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='lembrete de vencimento enviado em'),
        ),
    ]
