# Generated by Django 5.2.17 on 2026-09-12 19:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_documento_and_more'),
        ('faturamento', '0004_fatura_lembrete_previo_enviado_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatura',
            name='numero',
            field=models.CharField(max_length=20, verbose_name='número'),
        ),
        migrations.AddConstraint(
            model_name='fatura',
            constraint=models.UniqueConstraint(fields=('owner', 'numero'), name='uniq_fatura_owner_numero'),
        ),
    ]
