# Generated by Django 5.2.17 on 2026-09-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0005_alter_fatura_numero_fatura_uniq_fatura_owner_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes/%Y/%m/', verbose_name='comprovante'),
        ),
    ]
