# Generated by Django 5.2.17 on 2026-09-17 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0006_comprovante_pagamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('natureza', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], default='despesa', help_text='Define se a categoria agrupa receitas ou despesas no DRE.', max_length=20, verbose_name='natureza')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_financeiras', to=settings.AUTH_USER_MODEL, verbose_name='dono')),
            ],
            options={
                'verbose_name': 'categoria financeira',
                'verbose_name_plural': 'categorias financeiras',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='cobrancarecorrente',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobrancas_recorrentes', to='faturamento.categoriafinanceira', verbose_name='categoria'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faturas', to='faturamento.categoriafinanceira', verbose_name='categoria'),
        ),
        migrations.AddConstraint(
            model_name='categoriafinanceira',
            constraint=models.UniqueConstraint(fields=('owner', 'nome'), name='uniq_categoria_owner_nome'),
        ),
    ]
