# Generated by Django 5.2.17 on 2026-09-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0007_categoriafinanceira_cobrancarecorrente_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobrancarecorrente',
            name='tipo',
            field=models.CharField(choices=[('a_receber', 'Receber'), ('a_pagar', 'Pagar')], default='a_receber', max_length=20, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='tipo',
            field=models.CharField(choices=[('a_receber', 'Receber'), ('a_pagar', 'Pagar')], default='a_receber', max_length=20, verbose_name='tipo'),
        ),
    ]
